# Generated by Django 4.2.16 on 2024-10-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
