# Generated by Django 4.2.16 on 2024-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
